image: burnpanck/llvm-armeabi-newlib:8.0
stages:
- build
blinky_pca10056_mbr_nrf52840_xxaa:
  stage: build
  tags:
  - docker
  script:
  - mkdir build
  - cd build
  - cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=/toolchain/cmake/armv7em-eabi-none-toolchain.cmake
    ..
  - cmake --build . --target blinky_pca10056_mbr_nrf52840_xxaa
blinky_pca10056_nrf52840_xxaa:
  stage: build
  tags:
  - docker
  script:
  - mkdir build
  - cd build
  - cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=/toolchain/cmake/armv7em-eabi-none-toolchain.cmake
    ..
  - cmake --build . --target blinky_pca10056_nrf52840_xxaa
rtc_pca10056_nrf52840_xxaa:
  stage: build
  tags:
  - docker
  script:
  - mkdir build
  - cd build
  - cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=/toolchain/cmake/armv7em-eabi-none-toolchain.cmake
    ..
  - cmake --build . --target rtc_pca10056_nrf52840_xxaa
timer_pca10056_nrf52840_xxaa:
  stage: build
  tags:
  - docker
  script:
  - mkdir build
  - cd build
  - cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=/toolchain/cmake/armv7em-eabi-none-toolchain.cmake
    ..
  - cmake --build . --target timer_pca10056_nrf52840_xxaa
twi_master_using_nrf_twi_mngr_pca10056_nrf52840_xxaa:
  stage: build
  tags:
  - docker
  script:
  - mkdir build
  - cd build
  - cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=/toolchain/cmake/armv7em-eabi-none-toolchain.cmake
    ..
  - cmake --build . --target twi_master_using_nrf_twi_mngr_pca10056_nrf52840_xxaa
usbd_cdc_acm_pca10056_nrf52840_xxaa:
  stage: build
  tags:
  - docker
  script:
  - mkdir build
  - cd build
  - cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=/toolchain/cmake/armv7em-eabi-none-toolchain.cmake
    ..
  - cmake --build . --target usbd_cdc_acm_pca10056_nrf52840_xxaa
usbd_msc_pca10056_nrf52840_xxaa:
  stage: build
  tags:
  - docker
  script:
  - mkdir build
  - cd build
  - cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=/toolchain/cmake/armv7em-eabi-none-toolchain.cmake
    ..
  - cmake --build . --target usbd_msc_pca10056_nrf52840_xxaa
usbd_pca10056_nrf52840_xxaa:
  stage: build
  tags:
  - docker
  script:
  - mkdir build
  - cd build
  - cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=/toolchain/cmake/armv7em-eabi-none-toolchain.cmake
    ..
  - cmake --build . --target usbd_pca10056_nrf52840_xxaa
