stages:
- build

# refer to https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
# for most of the following
.docker-build-base: &docker-build-base
  stage: build
  tags:
  - docker
  image: docker:git
  services:
  - docker:dind
  variables:
    CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}/nrf5-sdk-clang-${CI_JOB_NAME}:${CI_BUILD_REF_NAME}
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -f nRF52-SDK-${CI_JOB_NAME}-clang.dockerfile -t ${CONTAINER_IMAGE} --build-arg CI_BUILD_REF_NAME=${CI_BUILD_REF_NAME} --build-arg http_proxy --build-arg no_proxy .
  - docker push ${CONTAINER_IMAGE}

"15.3":
  <<: *docker-build-base
